url: https://y7kim.github.io
baseurl: /juliepark

# Site settings
title: Julie Park | Portfolio
email: jspark721@gmail.com
description: "Julie Park Portfolio"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/juliepark
  - title: github
    url: http://github.com/jspark721

# Postal address (add as many lines as necessary)
address:
  - line: -
  - line: -

# Build settings
markdown: kramdown
permalink: pretty